services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://tczewik:tczewik@mariadb:3306/tczewik
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-central-1
      - SECRET_KEY=zmien-mnie-przed-wdrozeniem
      - TZ=Europe/Warsaw
      - ADMIN_LOGIN=admin
      - ADMIN_PASSWORD=admin123
      - PKP_API_KEY=XrRMXOBa5YBQ7m92d8syNCRJPRRm3lfK5zKaF1rGyqIX84CukvkwOpRnCSu53R4p1VSmOLOTfkrOn63P0pimnw
      # - REPORTS_S3_BUCKET=nazwa-twojego-bucketa

  mariadb:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tczewik
      - MYSQL_USER=tczewik
      - MYSQL_PASSWORD=tczewik
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data:
